### PR TITLE
Switch to go-swagger for client lib and checks for IRON_TOKEN

### PR DESCRIPTION
**Pull request by treeder**
This is just for review, to see if this looks like the right way to do the auth.

### CODE REVIEW

**Comment by pedronasser** [comment]
@treeder 
Could we replace IRON_TOKEN for just AUTH_TOKEN?
I guess some enterprise users would like to have their own authentication and might use that environment var as well.

**Comment by treeder** [comment]
@pedronasser looks like I didn't answer your question, the IRON_TOKE N iss there because that's what all Iron users use right now.

**Comment by treeder** [comment]
@pedronasser can you fix conflicts, then I'll review.

**Comment by treeder** [comment]
@pedronasser conflicts?

**Comment by pedronasser** [comment]
@treeder fixing it

**Comment by pedronasser** [comment]
@treeder Waiting for this #476 to be merged

**Pull request merged**
