### PR TITLE
fn: apps commands improvements

### PR DESCRIPTION
**Pull request by pedronasser**
Following this issue: #467 

- Added `fn apps inspect`
- Added `fn apps update`

### CODE REVIEW

**Comment by ccirello** [comment]
how do you do `config unset`?

**Comment by pedronasser** [comment]
@ccirello right now should be like this: `fn apps routes --config myconf=,`
But that looks not so good.
How about like this? Any suggestion?
`fn apps routes --config "-myconf"`

**Comment by ccirello** [comment]
If setting a configuration key to empty removes it, how do you set empty values?

**Comment by treeder** [comment]
What if we do something along the lines of heroku style configs? https://devcenter.heroku.com/articles/config-vars

**Comment by treeder** [comment]
config:set and config:unset

**Comment by ccirello** [comment]
@treeder that's how it was before, but I am giving Pedro some room to think about this change. It was like you're suggesting, but this PR changes this.

**Comment by pedronasser** [comment]
@treeder 
A command just to set and unset the config?
Couldn't it be like this?
```
fn apps update --config:set myconf --config:unset myconf2
```

**Comment by pedronasser** [comment]
I added `config set` and `config unset` back.

**Comment by treeder** [comment]
Are there any docs that go along with this?  Would like to see examples of these changes.

**Comment by pedronasser** [comment]
@treeder Is this enough? https://github.com/iron-io/functions/issues/467

**Comment by treeder** [comment]
Yes, that's great. Can you add that to the docs, that's actually a lot more clear than what's currently there: https://github.com/iron-io/functions/blob/master/fn/README.md

**Pull request merged**
