### PR TITLE
Config EnvVars passed without leading _

### PR DESCRIPTION
**Pull request by Gouthamve**
* Earlier X=Y was passed as _X=Y

### CODE REVIEW

**Comment by treeder** [comment]
thanks!

**Comment by seiflotfy** [comment]
There was a reason we had the _ ? Trying to find out why again

**Comment by jmank88** [comment]
Is some prefix necessary to prevent clashes with vars like ```METHOD``` and ```ROUTE```?

**Comment by seiflotfy** [comment]
LGTM can you check for any documentation that needs changing.

**Pull request merged**
