### PR TITLE
Fix route update

### PR DESCRIPTION
**Pull request by pedronasser**
- Added EnsureImage to route update

Relates to #288

### CODE REVIEW

**Comment by treeder** [comment]
@ccirello can you review

**Comment by ccirello** [comment]
I am testing it...

**Comment by ccirello** [comment]
It might have fixed something, but definitely it did not help with https://github.com/iron-io/functions/issues/288

**Comment by ccirello** [comment]
This did not help with #288 - but I think I see the point of this change. In the end, this change would be necessary to ensure that route updates work. So partial route updates, ie the ones that are not changing the image, still go through.

**Pull request merged**
